import type { RoleCode } from "../auth/session";

/// Transcribed verbatim from docs/security/RBAC_MATRIX.md §2 (role→permission) and §3
/// (role→ScopeKind) — the backend's real `database/seeds/seed.ts` `GRANTS` constant is the
/// actual source of truth; this is its UX-facing mirror (docs/frontend/
/// FRONTEND_PERMISSION_MAP.md). **UX ONLY** — every one of these grants is re-checked
/// server-side on every request regardless of what this data drives in the UI
/// (`frontend_prompts` MASTER_CONTEXT: "Frontend không được tự quyết định authorization").
/// If this ever disagrees with RBAC_MATRIX.md/the backend, the backend wins — update this
/// file, not the other way around.

export type Resource =
  | "leads"
  | "students"
  | "cases"
  | "contracts"
  | "payments"
  | "tasks"
  | "assessments"
  | "roadmaps"
  | "profile_evidence"
  | "writing"
  | "documents"
  | "admission_master"
  | "university_choices"
  | "applications"
  | "offers"
  | "scholarship_applications"
  | "visa"
  | "visa_checklist_templates"
  | "pre_departure"
  | "enrollment"
  | "partner"
  | "partner_programs"
  | "partner_documents"
  | "partner_student_links"
  | "commission_rules"
  | "commission_transactions"
  | "reports"
  | "portal"
  | "jobs"
  | "users"
  | "audit_logs";

/// Not every resource supports every action — this is deliberately loose (`string`, not a
/// per-resource discriminated union) because the check is against real backend permission
/// rows at runtime, and a stricter compile-time type here would need to be regenerated by
/// hand every time a domain phase adds a new action, with no safety benefit (the backend is
/// what actually enforces it either way).
export type Action = string;

type GrantMap = Partial<Record<Resource, Action[]>>;

const EXECUTIVE_DIRECTOR_GRANTS: GrantMap = {
  leads: ["view", "create", "edit", "assign", "convert"],
  students: ["view", "create", "edit", "archive", "export"],
  cases: ["view", "edit", "assign", "close"],
  contracts: ["view", "create", "edit", "approve", "send", "sign", "amend", "export"],
  payments: ["view", "export"],
  tasks: ["view", "create", "edit", "assign"],
  assessments: ["view", "create", "edit", "approve"],
  roadmaps: ["view", "create", "edit", "approve"],
  profile_evidence: ["view", "create", "edit"],
  writing: ["view", "create", "edit"],
  documents: ["view", "create", "download", "edit", "share", "archive"],
  admission_master: ["view", "create", "edit", "verify"],
  university_choices: ["view", "create", "edit"],
  applications: ["view", "create", "edit"],
  offers: ["view", "create", "edit"],
  scholarship_applications: ["view", "create", "edit"],
  visa: ["view", "create", "edit"],
  visa_checklist_templates: ["view", "create", "edit"],
  pre_departure: ["view", "create", "edit"],
  enrollment: ["view", "create", "edit"],
  partner: ["view", "create", "edit"],
  partner_programs: ["view", "create", "edit"],
  partner_documents: ["view", "create", "edit"],
  partner_student_links: ["view", "create", "edit"],
  commission_rules: ["view", "create", "edit"],
  commission_transactions: ["view", "create", "edit"],
  reports: ["view", "export"],
  users: ["view"],
};

// DEPARTMENT_MANAGER: identical to EXECUTIVE_DIRECTOR except zero `users` grant (ED gets
// `users:view`, DM does not — RBAC_MATRIX.md §2 note: "separation of duties").
const { users: _edUsersGrant, ...DEPARTMENT_MANAGER_GRANTS } = EXECUTIVE_DIRECTOR_GRANTS;
void _edUsersGrant;

const CONSULTANT_GRANTS: GrantMap = {
  students: ["view", "edit"],
  cases: ["view", "edit", "assign", "close"],
  tasks: ["view", "create", "edit", "assign"],
  assessments: ["view", "create", "edit"],
  roadmaps: ["view", "create", "edit"],
  profile_evidence: ["view", "create", "edit"],
  writing: ["view", "create", "edit"],
  documents: ["view", "create", "download", "edit", "share", "archive"],
  admission_master: ["view"],
  university_choices: ["view", "create", "edit"],
  applications: ["view", "create", "edit"],
  offers: ["view", "create", "edit"],
  scholarship_applications: ["view", "create", "edit"],
  visa: ["view", "create", "edit"],
  visa_checklist_templates: ["view"],
  pre_departure: ["view", "create", "edit"],
  enrollment: ["view", "create", "edit"],
  reports: ["view"],
};

const DOCUMENT_SPECIALIST_GRANTS: GrantMap = {
  students: ["view"],
  cases: ["view"],
  tasks: ["view", "create", "edit", "assign"],
  assessments: ["view"],
  roadmaps: ["view"],
  profile_evidence: ["view"],
  writing: ["view"],
  documents: ["view", "create", "download", "edit", "share", "archive"],
  admission_master: ["view"],
  university_choices: ["view"],
  applications: ["view", "create", "edit"],
  offers: ["view"],
  scholarship_applications: ["view"],
  visa: ["view", "create", "edit"],
  visa_checklist_templates: ["view"],
  pre_departure: ["view", "create", "edit"],
  enrollment: ["view"],
  partner: ["view"],
  partner_documents: ["view"],
  reports: ["view"],
};

const SALES_MARKETING_GRANTS: GrantMap = {
  leads: ["view", "create", "edit", "assign", "convert"],
  admission_master: ["view"],
  visa_checklist_templates: ["view"],
  reports: ["view"],
};

const ADMIN_FINANCE_GRANTS: GrantMap = {
  contracts: ["view", "create", "edit", "send", "sign", "export"],
  payments: ["view", "create", "record", "refund", "waive", "export"],
  partner: ["view"],
  partner_programs: ["view"],
  partner_documents: ["view"],
  partner_student_links: ["view"],
  commission_rules: ["view", "create", "edit"],
  commission_transactions: ["view", "create", "edit"],
  reports: ["view"],
};

const STUDENT_PARENT_GRANTS: GrantMap = {
  students: ["view"],
  cases: ["view"],
  contracts: ["view"],
  payments: ["view"],
  assessments: ["view"],
  roadmaps: ["view"],
  profile_evidence: ["view"],
  writing: ["view"],
  documents: ["view", "create", "download"],
  admission_master: ["view"],
  university_choices: ["view"],
  applications: ["view"],
  offers: ["view"],
  scholarship_applications: ["view"],
  visa: ["view"],
  visa_checklist_templates: ["view"],
  pre_departure: ["view"],
  portal: ["access"],
};

const SYSTEM_ADMIN_GRANTS: GrantMap = {
  users: ["view", "suspend", "offboard"],
  audit_logs: ["view"],
  jobs: ["view"],
};

export const ROLE_GRANTS: Record<RoleCode, GrantMap> = {
  EXECUTIVE_DIRECTOR: EXECUTIVE_DIRECTOR_GRANTS,
  DEPARTMENT_MANAGER: DEPARTMENT_MANAGER_GRANTS,
  CONSULTANT: CONSULTANT_GRANTS,
  DOCUMENT_SPECIALIST: DOCUMENT_SPECIALIST_GRANTS,
  SALES_MARKETING: SALES_MARKETING_GRANTS,
  ADMIN_FINANCE: ADMIN_FINANCE_GRANTS,
  STUDENT_PARENT: STUDENT_PARENT_GRANTS,
  SYSTEM_ADMIN: SYSTEM_ADMIN_GRANTS,
};

/// UX-only scope hint (docs/frontend/FRONTEND_PERMISSION_MAP.md per-role "Scope" line) — a
/// list page MAY use this to decide whether to show an owner/case filter control, but must
/// NEVER use it to decide whether a specific record is accessible (F02 instruction §12: "Không
/// cho phép /students/:id được coi là accessible chỉ vì có route" — only the backend's
/// actual 200 vs 404 response on that record decides that).
export type ScopeKind = "GLOBAL" | "CASE_MEMBER" | "OWN_STUDENT" | "OWN_LEAD" | "NONE";

export const STUDENT_CASE_SCOPE: Record<RoleCode, ScopeKind> = {
  EXECUTIVE_DIRECTOR: "GLOBAL",
  DEPARTMENT_MANAGER: "GLOBAL",
  CONSULTANT: "CASE_MEMBER",
  DOCUMENT_SPECIALIST: "CASE_MEMBER",
  SALES_MARKETING: "NONE",
  ADMIN_FINANCE: "NONE",
  STUDENT_PARENT: "OWN_STUDENT",
  SYSTEM_ADMIN: "NONE",
};

export const LEAD_SCOPE: Record<RoleCode, ScopeKind> = {
  EXECUTIVE_DIRECTOR: "GLOBAL",
  DEPARTMENT_MANAGER: "GLOBAL",
  CONSULTANT: "NONE",
  DOCUMENT_SPECIALIST: "NONE",
  SALES_MARKETING: "OWN_LEAD",
  ADMIN_FINANCE: "NONE",
  STUDENT_PARENT: "NONE",
  SYSTEM_ADMIN: "NONE",
};

export const CONTRACT_PAYMENT_SCOPE: Record<RoleCode, ScopeKind> = {
  EXECUTIVE_DIRECTOR: "GLOBAL",
  DEPARTMENT_MANAGER: "GLOBAL",
  CONSULTANT: "NONE",
  DOCUMENT_SPECIALIST: "NONE",
  SALES_MARKETING: "NONE",
  ADMIN_FINANCE: "GLOBAL",
  STUDENT_PARENT: "OWN_STUDENT",
  SYSTEM_ADMIN: "NONE",
};
