/// Static ISO 3166-1 alpha-2 country list with Vietnamese display names, used by
/// `CountryPicker` so staff pick a country by name instead of typing its ISO-2 code by hand.
/// The stored value everywhere in the app (Lead.countryInterest, Student.targetCountry,
/// Visa.countryCode, ...) stays the 2-letter code — this file only drives the picker's UI.
export interface Country {
  code: string;
  nameVi: string;
  nameEn: string;
}

export const COUNTRIES: Country[] = [
  { code: "US", nameVi: "Hoa Kỳ", nameEn: "United States" },
  { code: "GB", nameVi: "Anh", nameEn: "United Kingdom" },
  { code: "CA", nameVi: "Canada", nameEn: "Canada" },
  { code: "AU", nameVi: "Úc", nameEn: "Australia" },
  { code: "NZ", nameVi: "New Zealand", nameEn: "New Zealand" },
  { code: "IE", nameVi: "Ireland", nameEn: "Ireland" },
  { code: "SG", nameVi: "Singapore", nameEn: "Singapore" },
  { code: "JP", nameVi: "Nhật Bản", nameEn: "Japan" },
  { code: "KR", nameVi: "Hàn Quốc", nameEn: "South Korea" },
  { code: "CN", nameVi: "Trung Quốc", nameEn: "China" },
  { code: "TW", nameVi: "Đài Loan", nameEn: "Taiwan" },
  { code: "HK", nameVi: "Hồng Kông", nameEn: "Hong Kong" },
  { code: "DE", nameVi: "Đức", nameEn: "Germany" },
  { code: "FR", nameVi: "Pháp", nameEn: "France" },
  { code: "NL", nameVi: "Hà Lan", nameEn: "Netherlands" },
  { code: "CH", nameVi: "Thụy Sĩ", nameEn: "Switzerland" },
  { code: "SE", nameVi: "Thụy Điển", nameEn: "Sweden" },
  { code: "NO", nameVi: "Na Uy", nameEn: "Norway" },
  { code: "DK", nameVi: "Đan Mạch", nameEn: "Denmark" },
  { code: "FI", nameVi: "Phần Lan", nameEn: "Finland" },
  { code: "IT", nameVi: "Ý", nameEn: "Italy" },
  { code: "ES", nameVi: "Tây Ban Nha", nameEn: "Spain" },
  { code: "PT", nameVi: "Bồ Đào Nha", nameEn: "Portugal" },
  { code: "AT", nameVi: "Áo", nameEn: "Austria" },
  { code: "BE", nameVi: "Bỉ", nameEn: "Belgium" },
  { code: "PL", nameVi: "Ba Lan", nameEn: "Poland" },
  { code: "CZ", nameVi: "Séc", nameEn: "Czech Republic" },
  { code: "HU", nameVi: "Hungary", nameEn: "Hungary" },
  { code: "GR", nameVi: "Hy Lạp", nameEn: "Greece" },
  { code: "RU", nameVi: "Nga", nameEn: "Russia" },
  { code: "TR", nameVi: "Thổ Nhĩ Kỳ", nameEn: "Turkey" },
  { code: "AE", nameVi: "Các Tiểu vương quốc Ả Rập Thống nhất", nameEn: "United Arab Emirates" },
  { code: "MY", nameVi: "Malaysia", nameEn: "Malaysia" },
  { code: "TH", nameVi: "Thái Lan", nameEn: "Thailand" },
  { code: "PH", nameVi: "Philippines", nameEn: "Philippines" },
  { code: "ID", nameVi: "Indonesia", nameEn: "Indonesia" },
  { code: "IN", nameVi: "Ấn Độ", nameEn: "India" },
  { code: "VN", nameVi: "Việt Nam", nameEn: "Vietnam" },
  { code: "KH", nameVi: "Campuchia", nameEn: "Cambodia" },
  { code: "LA", nameVi: "Lào", nameEn: "Laos" },
  { code: "MM", nameVi: "Myanmar", nameEn: "Myanmar" },
  { code: "BD", nameVi: "Bangladesh", nameEn: "Bangladesh" },
  { code: "PK", nameVi: "Pakistan", nameEn: "Pakistan" },
  { code: "LK", nameVi: "Sri Lanka", nameEn: "Sri Lanka" },
  { code: "NP", nameVi: "Nepal", nameEn: "Nepal" },
  { code: "MX", nameVi: "Mexico", nameEn: "Mexico" },
  { code: "BR", nameVi: "Brazil", nameEn: "Brazil" },
  { code: "AR", nameVi: "Argentina", nameEn: "Argentina" },
  { code: "CL", nameVi: "Chile", nameEn: "Chile" },
  { code: "CO", nameVi: "Colombia", nameEn: "Colombia" },
  { code: "ZA", nameVi: "Nam Phi", nameEn: "South Africa" },
  { code: "EG", nameVi: "Ai Cập", nameEn: "Egypt" },
  { code: "SA", nameVi: "Ả Rập Xê Út", nameEn: "Saudi Arabia" },
  { code: "IL", nameVi: "Israel", nameEn: "Israel" },
  { code: "QA", nameVi: "Qatar", nameEn: "Qatar" },
  { code: "KW", nameVi: "Kuwait", nameEn: "Kuwait" },
  { code: "IS", nameVi: "Iceland", nameEn: "Iceland" },
  { code: "LU", nameVi: "Luxembourg", nameEn: "Luxembourg" },
  { code: "MT", nameVi: "Malta", nameEn: "Malta" },
  { code: "CY", nameVi: "Síp", nameEn: "Cyprus" },
  { code: "EE", nameVi: "Estonia", nameEn: "Estonia" },
  { code: "LV", nameVi: "Latvia", nameEn: "Latvia" },
  { code: "LT", nameVi: "Litva", nameEn: "Lithuania" },
  { code: "SK", nameVi: "Slovakia", nameEn: "Slovakia" },
  { code: "SI", nameVi: "Slovenia", nameEn: "Slovenia" },
  { code: "HR", nameVi: "Croatia", nameEn: "Croatia" },
  { code: "RO", nameVi: "Romania", nameEn: "Romania" },
  { code: "BG", nameVi: "Bulgaria", nameEn: "Bulgaria" },
  { code: "UA", nameVi: "Ukraine", nameEn: "Ukraine" },
  { code: "RS", nameVi: "Serbia", nameEn: "Serbia" },
  { code: "AL", nameVi: "Albania", nameEn: "Albania" },
  { code: "AD", nameVi: "Andorra", nameEn: "Andorra" },
  { code: "MC", nameVi: "Monaco", nameEn: "Monaco" },
  { code: "LI", nameVi: "Liechtenstein", nameEn: "Liechtenstein" },
  { code: "MD", nameVi: "Moldova", nameEn: "Moldova" },
  { code: "BY", nameVi: "Belarus", nameEn: "Belarus" },
  { code: "GE", nameVi: "Gruzia", nameEn: "Georgia" },
  { code: "AM", nameVi: "Armenia", nameEn: "Armenia" },
  { code: "AZ", nameVi: "Azerbaijan", nameEn: "Azerbaijan" },
  { code: "KZ", nameVi: "Kazakhstan", nameEn: "Kazakhstan" },
  { code: "UZ", nameVi: "Uzbekistan", nameEn: "Uzbekistan" },
  { code: "MN", nameVi: "Mông Cổ", nameEn: "Mongolia" },
  { code: "AF", nameVi: "Afghanistan", nameEn: "Afghanistan" },
  { code: "IR", nameVi: "Iran", nameEn: "Iran" },
  { code: "IQ", nameVi: "Iraq", nameEn: "Iraq" },
  { code: "JO", nameVi: "Jordan", nameEn: "Jordan" },
  { code: "LB", nameVi: "Lebanon", nameEn: "Lebanon" },
  { code: "OM", nameVi: "Oman", nameEn: "Oman" },
  { code: "BH", nameVi: "Bahrain", nameEn: "Bahrain" },
  { code: "YE", nameVi: "Yemen", nameEn: "Yemen" },
  { code: "SY", nameVi: "Syria", nameEn: "Syria" },
  { code: "BN", nameVi: "Brunei", nameEn: "Brunei" },
  { code: "TL", nameVi: "Đông Timor", nameEn: "Timor-Leste" },
  { code: "FJ", nameVi: "Fiji", nameEn: "Fiji" },
  { code: "PG", nameVi: "Papua New Guinea", nameEn: "Papua New Guinea" },
  { code: "PE", nameVi: "Peru", nameEn: "Peru" },
  { code: "VE", nameVi: "Venezuela", nameEn: "Venezuela" },
  { code: "EC", nameVi: "Ecuador", nameEn: "Ecuador" },
  { code: "BO", nameVi: "Bolivia", nameEn: "Bolivia" },
  { code: "PY", nameVi: "Paraguay", nameEn: "Paraguay" },
  { code: "UY", nameVi: "Uruguay", nameEn: "Uruguay" },
  { code: "CU", nameVi: "Cuba", nameEn: "Cuba" },
  { code: "DO", nameVi: "Cộng hòa Dominica", nameEn: "Dominican Republic" },
  { code: "JM", nameVi: "Jamaica", nameEn: "Jamaica" },
  { code: "PA", nameVi: "Panama", nameEn: "Panama" },
  { code: "CR", nameVi: "Costa Rica", nameEn: "Costa Rica" },
  { code: "GT", nameVi: "Guatemala", nameEn: "Guatemala" },
  { code: "HN", nameVi: "Honduras", nameEn: "Honduras" },
  { code: "SV", nameVi: "El Salvador", nameEn: "El Salvador" },
  { code: "NI", nameVi: "Nicaragua", nameEn: "Nicaragua" },
  { code: "NG", nameVi: "Nigeria", nameEn: "Nigeria" },
  { code: "KE", nameVi: "Kenya", nameEn: "Kenya" },
  { code: "GH", nameVi: "Ghana", nameEn: "Ghana" },
  { code: "ET", nameVi: "Ethiopia", nameEn: "Ethiopia" },
  { code: "TZ", nameVi: "Tanzania", nameEn: "Tanzania" },
  { code: "UG", nameVi: "Uganda", nameEn: "Uganda" },
  { code: "MA", nameVi: "Morocco", nameEn: "Morocco" },
  { code: "DZ", nameVi: "Algeria", nameEn: "Algeria" },
  { code: "TN", nameVi: "Tunisia", nameEn: "Tunisia" },
  { code: "LY", nameVi: "Libya", nameEn: "Libya" },
  { code: "SD", nameVi: "Sudan", nameEn: "Sudan" },
  { code: "SN", nameVi: "Senegal", nameEn: "Senegal" },
  { code: "CI", nameVi: "Bờ Biển Ngà", nameEn: "Côte d'Ivoire" },
  { code: "CM", nameVi: "Cameroon", nameEn: "Cameroon" },
  { code: "ZW", nameVi: "Zimbabwe", nameEn: "Zimbabwe" },
  { code: "ZM", nameVi: "Zambia", nameEn: "Zambia" },
  { code: "MZ", nameVi: "Mozambique", nameEn: "Mozambique" },
  { code: "AO", nameVi: "Angola", nameEn: "Angola" },
  { code: "NA", nameVi: "Namibia", nameEn: "Namibia" },
  { code: "BW", nameVi: "Botswana", nameEn: "Botswana" },
  { code: "RW", nameVi: "Rwanda", nameEn: "Rwanda" },
  { code: "MU", nameVi: "Mauritius", nameEn: "Mauritius" },
];

const CODE_INDEX = new Map(COUNTRIES.map((c) => [c.code, c]));

export function findCountryByCode(code: string | undefined | null): Country | undefined {
  if (!code) return undefined;
  return CODE_INDEX.get(code.trim().toUpperCase());
}
